"""init

Revision ID: c8d3c77b2486
Revises: 
Create Date: 2023-11-01 16:15:18.319310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8d3c77b2486'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link_trailer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_film', sa.String(), nullable=True),
    sa.Column('id_video', sa.String(), nullable=True),
    sa.Column('link_trailer', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('date_update', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('link_trailer')
    # ### end Alembic commands ###
