"""2

Revision ID: 21ef7ca928fd
Revises: 89588ba3dd2b
Create Date: 2023-11-06 12:24:55.948499

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '21ef7ca928fd'
down_revision: Union[str, None] = '89588ba3dd2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('film_info',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('id_film', sa.String(), nullable=True),
                    sa.Column('actual_trailer_link', sa.String(), nullable=True),
                    sa.Column('cover_image', sa.String(), nullable=True),
                    sa.Column('title', sa.String(), nullable=True),
                    sa.Column('genre', sa.String(), nullable=True),
                    sa.Column('releases', sa.String(), nullable=True),
                    sa.Column('annotation', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('film_info')
    # ### end Alembic commands ###
