"""3

Revision ID: 05afbd478892
Revises: 21ef7ca928fd
Create Date: 2023-11-14 11:04:21.149150

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '05afbd478892'
down_revision: Union[str, None] = '21ef7ca928fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link_trailer', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('link_trailer', 'title')
    # ### end Alembic commands ###
