"""5

Revision ID: 68ce464bc128
Revises: 5c39d47976f0
Create Date: 2023-11-20 09:48:57.851176

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '68ce464bc128'
down_revision: Union[str, None] = '5c39d47976f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link_trailer', sa.Column('link_film', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('link_trailer', 'link_film')
    # ### end Alembic commands ###
