"""4

Revision ID: 5c39d47976f0
Revises: 05afbd478892
Create Date: 2023-11-20 09:45:12.019846

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5c39d47976f0'
down_revision: Union[str, None] = '05afbd478892'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link_trailer', sa.Column('genre', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('link_trailer', 'genre')
    # ### end Alembic commands ###
