"""6

Revision ID: 9ff69449f0b6
Revises: 68ce464bc128
Create Date: 2023-11-20 11:46:09.381828

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9ff69449f0b6'
down_revision: Union[str, None] = '68ce464bc128'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link_trailer', sa.Column('cover', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('link_trailer', 'cover')
    # ### end Alembic commands ###
